language: python

python:
  - 2.7
  - 3.3

services:
  - postgresql

install:
  - sudo apt-get install postgresql-9.1-postgis -q > /dev/null

before_script:
  - psql -c "CREATE ROLE gis PASSWORD 'gis' SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN;" -U postgres > /dev/null
  - psql -c 'CREATE DATABASE gis;' -U postgres > /dev/null
  - psql -d gis -f /usr/share/postgresql/9.1/contrib/postgis-1.5/postgis.sql -U postgres > /dev/null
  - psql -d gis -f /usr/share/postgresql/9.1/contrib/postgis-1.5/spatial_ref_sys.sql -U postgres > /dev/null

script:
  - python setup.py nosetests -v
